#!/usr/bin/env bun
/**
 * Build script to embed builtin-agent .md prompts into TypeScript
 * Run: bun run script/build-agent-prompts.ts
 * 
 * This generates src/features/builtin-agents/prompts.ts with the .md content
 * embedded as template literals, allowing TypeScript to compile without errors.
 */

import { readFileSync, writeFileSync, existsSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

var __dirname = dirname(fileURLToPath(import.meta.url))
var rootDir = join(__dirname, "..")
var builtinAgentsDir = join(rootDir, "src", "features", "builtin-agents")
var outputFile = join(builtinAgentsDir, "prompts.ts")

// Agent files to process
var agentFiles = [
  "pm.md",
  "po.md",
  "sm.md",
  "qa.md",
  "devops.md",
  "data-engineer.md",
  "ux-design-expert.md",
  "squad-creator.md",
  "analyst.md",
  "plan-analyzer.md",
  "plan-reviewer.md",
]

function escapeForTemplateLiteral(str) {
  // Escape backticks and ${} for template literals
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
}

function toPascalCase(str) {
  // Convert kebab-case to PascalCase
  return str
    .replace(".md", "")
    .split("-")
    .map(function(part) { return part.charAt(0).toUpperCase() + part.slice(1) })
    .join("")
}

function toCamelCase(str) {
  // Convert kebab-case to camelCase
  var pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

// Generate the TypeScript file
var exportLines = []

for (var i = 0; i < agentFiles.length; i++) {
  var file = agentFiles[i]
  var filePath = join(builtinAgentsDir, file)
  
  if (!existsSync(filePath)) {
    console.warn("Warning: " + file + " not found, skipping")
    continue
  }
  
  var content = readFileSync(filePath, "utf-8")
  var varName = toCamelCase(file)
  var escapedContent = escapeForTemplateLiteral(content)
  
  // Add export - using regular string since we escaped everything
  exportLines.push("export const " + varName + "Prompt = `" + escapedContent + "`")
}

var exportSection = exportLines.join("\n\n")

// Build the map entry for each agent
var mapEntries = agentFiles.map(function(file) {
  var varName = toCamelCase(file)
  var key = varName.replace("Prompt", "")
  return '  "' + key + '": ' + varName + "Prompt"
}).join(",\n")

var output = "/**\n" +
  " * Auto-generated file - DO NOT EDIT\n" +
  " * Generated by: script/build-agent-prompts.ts\n" +
  " * \n" +
  " * This file embeds builtin-agent .md prompts as template literals\n" +
  " * for TypeScript compatibility while maintaining build-time embedding.\n" +
  " */\n\n" +
  exportSection + "\n\n" +
  "export const BUILTIN_AGENT_PROMPTS = {\n" +
  mapEntries + "\n" +
  "} as const\n\n" +
  "export type BuiltinAgentName = keyof typeof BUILTIN_AGENT_PROMPTS\n"

// Write the output file
writeFileSync(outputFile, output, "utf-8")

console.log("Generated " + outputFile + " with " + agentFiles.length + " agent prompts")
